#!/bin/bash

# python specific
sudo apt install python3-dev python3-pip virtualenv virtualenvwrapper

# vim stuff
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt install neovim python3-neovim
sudo pip3 install sexpdata websocket-client
sudo pip3 install --upgrade neovim
nvim -E -c UpdateRemotePlugins -c q
nvim -E -c PlugInstall -c q

# tmux stuff
sudo apt install tmux ruby
sudo gem install tmuxinator

# configuration stuff
git clone https://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
$HOME/.homesick/repos/homeshick/bin/homeshick clone https://gitlab.com/michaelmdeng/DotConfig.git

# gui stuff
sudo apt install x11-apps x11-server-utils
