#!/bin/bash

# general
sudo apt install jq

# python specific
sudo apt install python3-dev python3-pip virtualenv virtualenvwrapper

# vim stuff
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt install neovim python3-neovim
sudo pip3 install sexpdata websocket-client
sudo pip3 install --upgrade neovim
nvim -E -c UpdateRemotePlugins -c q
nvim -E -c PlugInstall -c q

# tmux stuff
sudo apt install tmux ruby
sudo gem install tmuxinator
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# configuration stuff
git clone https://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
$HOME/.homesick/repos/homeshick/bin/homeshick clone https://gitlab.com/michaelmdeng/DotConfig.git

# gui stuff
sudo apt install x11-apps x11-server-utils

# spark stuff
sudo apt install openjdk-8-jdk
echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
sudo apt-get update
sudo apt-get install sbt

# um stuff
sudo apt install pandoc
git clone https://github.com/sinclairtarget/um.git $HOME/um

# Azure stuff
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list
curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt update
sudo apt install apt-transport-https azure-cli

# jupyter
sudo apt install libkrb5-dev
sudo pip3 install jupyter
