setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal autoindent
setlocal smarttab
setlocal textwidth=79
setlocal colorcolumn=80
setlocal spell
setlocal wrap
setlocal linebreak
setlocal formatoptions+=bl
set conceallevel=0
let g:indentLine_enabled=0
