setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal autoindent
setlocal smarttab
setlocal textwidth=80
setlocal colorcolumn=81
setlocal spell
setlocal wrap
setlocal linebreak
setlocal formatoptions+=bl
set conceallevel=0
let g:indentLine_enabled=0
