setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal autoindent
setlocal smarttab
setlocal textwidth=89
setlocal colorcolumn=90
setlocal spell
setlocal wrap
setlocal linebreak
setlocal formatoptions+=bl
