setlocal autoindent
setlocal colorcolumn=89
setlocal expandtab
setlocal foldexpr=v:lua.vim.treesitter.foldexpr()
setlocal foldmethod=expr
setlocal foldlevel=99
setlocal formatoptions=croql
setlocal shiftwidth=4
setlocal smarttab
setlocal tabstop=4
setlocal textwidth=88
