setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal autoindent
setlocal smarttab
setlocal textwidth=80
setlocal colorcolumn=81
setlocal formatoptions=croql
setlocal foldmethod=indent
setlocal foldlevel=99
syntax on
