#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

pip install virtualenv virtualenvwrapper
pip install sexpdata websocket-client neovim
pip install pylint black flake8 mypy
pip install pyls python-lsp-server[all]
