name: ShellCheck

on: [push, pull_request]

jobs:
  build:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: make shellcheck
